name: qantamedia
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25742
title: Qanta Media
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#10b798'
    - '#ffffff'
    - '#18d39b'
    - '#1ce39d'
    - '#c8cacb'
  brandStrength: 0.4375
  lightness: 0.7163063252810389
  saturation: 0.9386060764081776
  rhythmicContrast: 0.21253702859394252
purpose: []
